Error seems to be (sometimes?) dict:   File "/usr/local/pypy-5.0/site-packages/txes2-0.5.0-py2.7.egg/txes2/exceptions.py", line 101, in raise_exceptions     bits = error.split('[', 1)     exceptions.AttributeError: 'dict' object has no attribute 'split' so while keeping the same code in the string case, try to handle the dict one by introducing a new exception types mapping. For start include the version_conflict_engine_exception.